# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 研究成果
    url: /publications/
    weight: 10
  - name: 成员
    url: /people/
    weight: 20
